CREATE DATABASE `gopay` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- 表随便写写，后续再优化修改

CREATE TABLE IF NOT EXISTS `account`
(
    `id`    BIGINT      NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
    `uname` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
    `pwd`   VARCHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
    `phone` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '手机号',
    `ctime` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `utime` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',

    PRIMARY KEY (`id`),
    UNIQUE KEY `uname` (`uname`),
    KEY `ctime` (`ctime`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT '账户表';

CREATE TABLE IF NOT EXISTS `company`
(
    `id`    BIGINT      NOT NULL AUTO_INCREMENT COMMENT '自增长ID',
    `name`  VARCHAR(32) NOT NULL DEFAULT '' COMMENT '公司名',
    `ctime` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `utime` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',

    PRIMARY KEY (`id`),
    KEY `name` (`name`),
    KEY `ctime` (`ctime`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT '公司表';
