log_level: "info"  # debug, info, warn, error

http:
  addr: ":2233"
  read_timeout: "60s"
  write_timeout: "60s"
  debug: false
  limiter:
    rate: 2000
    bucket_size: 1000

reload_interval: "1m"
reload_long_interval: "5m"